XDEV-1358 Server-Side Request Forgery (SSRF) in document templates
xtrf/html2pdf-server pull request #22
Opened 2023-10-25 21:31 UTC by wbubicz

2023-10-27 13:04 UTC, apaleczek-xtrf requested changes

2023-10-27 13:04 UTC, apaleczek-xtrf commented on backend/xtrf-html2pdf-server/src/test/java/eu/xtrf/html2pdf/server/converter/service/ConverterOpenPdfUserAgentTest.java
> +        converterOpenPdfUserAgent.resolveAndOpenStream(uri);
można skorzystać z nowego `ExceptionAssertions` w repo `xtrf-test-utils`

2023-10-27 13:04 UTC, apaleczek-xtrf commented on backend/xtrf-html2pdf-server/src/test/java/eu/xtrf/html2pdf/server/converter/service/ConverterOpenPdfUserAgentTest.java
> +        }
można skorzystać z nowego `ExceptionAssertions` w repo `xtrf-test-utils`

2023-10-27 13:04 UTC, apaleczek-xtrf commented on backend/xtrf-html2pdf-server/src/test/java/eu/xtrf/html2pdf/server/converter/service/ConverterOpenPdfUserAgentTest.java
> +            Assert.assertTrue(e.getCause() instanceof FileNotFoundException);
można skorzystać z nowego `ExceptionAssertions` w repo `xtrf-test-utils`

2023-10-27 13:37 UTC, wbubicz commented on backend/xtrf-html2pdf-server/src/main/java/eu/xtrf/html2pdf/server/converter/service/ConverterOpenPdfUserAgent.java
> +            return IOUtils.toInputStream(styleCss, StandardCharsets.UTF_8);
Przed zmianami jak jeszcze był zapisywany styles.css na dysku to używany był 
FileOutputStream.write(styles.getBytes()); który pod spodem używa Charset.defaultCharset() który zwraca UTF-8, ale w sumie lepiej faktycznie zamienić tutaj StandardCharsets.UTF_8 na Charset.defaultCharset() to będzie w zasadzie tak jak było wcześniej.

2023-10-27 17:45 UTC, apaleczek-xtrf requested changes

2023-10-27 17:45 UTC, apaleczek-xtrf commented on backend/xtrf-html2pdf-server/pom.xml
> +            <version>5.6.2</version>
używamy wersji, które są zdefiniowane w parent pom'ie

2023-10-27 17:47 UTC, apaleczek-xtrf requested changes

2023-10-27 17:47 UTC, apaleczek-xtrf commented on backend/xtrf-html2pdf-server/pom.xml
> +            <version>2.0.1-SNAPSHOT</version>
wersja powinna być ustawiona jako property, a w tym miejscu powinno być użyte odwołanie do property

2023-10-30 11:34 UTC, apaleczek-xtrf approved these changes

2023-10-30 11:34 UTC, merged